apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-by-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: app-ingress-nginx
  rules:
  - host: sub.scj00237.devenv.teamops.nifcloud.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: handson
            port:
              number: 8080
